version: "3"

services:
  app:
    image: sabberslt/claude2:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - SESSION=${SESSION}
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    command: node index.js
