version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - ./.env:/app/.env
    command: node index.js
